//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarthquakeMap.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarthquakeMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   100,石狩地方北部,43.4151931842515,141.49525560707
        ///101,石狩地方中部,43.010872239411,141.291800149006
        ///102,石狩地方南部,42.8401853638524,141.496898327669
        ///105,渡島地方北部,42.2715261571357,140.227924212031
        ///106,渡島地方東部,41.9171303977866,140.730104639953
        ///107,渡島地方西部,41.5890677088811,140.250720331631
        ///110,檜山地方,42.1200892176946,140.117224870458
        ///115,後志地方北部,43.1570832606841,140.766313140274
        ///116,後志地方東部,42.8279967803352,140.848074079286
        ///117,後志地方西部,42.8212795958583,140.381809567057
        ///119,北海道奥尻島,42.1553384492168,139.473175204362
        ///120,空知地方北部,43.8088241 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaPoint {
            get {
                return ResourceManager.GetString("AreaPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   110100,札幌中央区,43.0384041572337,141.302077451493
        ///110200,札幌北区,43.1347503224117,141.354056247971
        ///110300,札幌東区,43.1087430953872,141.40131974021
        ///110400,札幌白石区,43.0603253195276,141.425172890005
        ///110500,札幌豊平区,42.9998131682113,141.388947814027
        ///110600,札幌南区,42.9471219985831,141.181575479985
        ///110700,札幌西区,43.0639274394172,141.243072357961
        ///110800,札幌厚別区,43.043337954344,141.473777253169
        ///110900,札幌手稲区,43.115809519746,141.224470978469
        ///111000,札幌清田区,42.9620412063908,141.431388494746
        ///120200,函館市,41.8375442406375,140.925962642598
        ///1203 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CityPoint {
            get {
                return ResourceManager.GetString("CityPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   石狩市,石狩地方北部
        ///当別町,石狩地方北部
        ///新篠津村,石狩地方北部
        ///札幌中央区,石狩地方中部
        ///札幌北区,石狩地方中部
        ///札幌東区,石狩地方中部
        ///札幌白石区,石狩地方中部
        ///札幌豊平区,石狩地方中部
        ///札幌南区,石狩地方中部
        ///札幌西区,石狩地方中部
        ///札幌厚別区,石狩地方中部
        ///札幌手稲区,石狩地方中部
        ///札幌清田区,石狩地方中部
        ///江別市,石狩地方中部
        ///千歳市,石狩地方南部
        ///恵庭市,石狩地方南部
        ///北広島市,石狩地方南部
        ///八雲町,渡島地方北部
        ///長万部町,渡島地方北部
        ///函館市,渡島地方東部
        ///渡島北斗市,渡島地方東部
        ///七飯町,渡島地方東部
        ///鹿部町,渡島地方東部
        ///渡島森町,渡島地方東部
        ///渡島松前町,渡島地方西部
        ///福島町,渡島地方西部
        ///知内町,渡島地方西部
        ///木古内町,渡島地方西部
        ///檜山江差町,檜山地方
        ///上ノ国町,檜山地方
        ///厚沢部町,檜山地方
        ///乙部町,檜山地方
        ///今金町,檜山地方
        ///せたな町,檜山地方
        ///小樽市,後志地方北部
        ///積丹町,後志地方北部
        ///古平町,後志地方北部
        ///仁木町,後志地方北部
        ///余市町,後志地方北部
        ///赤井川村,後志地方北部
        ///ニセコ町,後志地方東部
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CityToArea {
            get {
                return ResourceManager.GetString("CityToArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   網走地方,北海道
        ///日高地方,北海道
        ///桧山地方,北海道
        ///胆振地方,北海道
        ///石狩地方,北海道
        ///上川地方,北海道
        ///釧路地方,北海道
        ///根室地方,北海道
        ///渡島地方,北海道
        ///留萌地方,北海道
        ///後志地方,北海道
        ///宗谷地方,北海道
        ///空知地方,北海道
        ///十勝地方,北海道
        ///青森県,東北
        ///岩手県,東北
        ///宮城県,東北
        ///秋田県,東北
        ///山形県,東北
        ///福島県,東北
        ///茨城県,関東
        ///栃木県,関東
        ///群馬県,関東
        ///埼玉県,関東
        ///千葉県,関東
        ///その他,null
        ///東京都,関東
        ///伊豆大島,伊豆諸島
        ///三宅島,伊豆諸島
        ///八丈島,伊豆諸島
        ///神奈川県,伊豆諸島
        ///相模湾,null
        ///新潟県,北陸
        ///富山県,北陸
        ///石川県,北陸
        ///福井県,北陸
        ///山梨県,甲信
        ///長野県,甲信
        ///岐阜県,東海
        ///静岡県,東海
        ///愛知県,東海
        ///三重県,東海
        ///滋賀県,近畿
        ///京都府,近畿
        ///大阪府,近畿
        ///兵庫県,近畿
        ///奈良県,近畿
        ///和歌山県,近畿
        ///鳥取県,中国
        ///島根県,中国
        ///岡山県,中国
        ///広島県,中国
        ///山口県,中国
        ///徳島県,四国
        ///香川県,四国
        ///愛媛県,四国
        ///高知県,四国
        ///福岡県,九州
        ///佐賀県,九 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string kyoshin_area {
            get {
                return ResourceManager.GetString("kyoshin_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
