//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllInformationViewer2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllInformationViewer2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   100,石狩地方北部,43.4151931842515,141.49525560707
        ///101,石狩地方中部,43.010872239411,141.291800149006
        ///102,石狩地方南部,42.8401853638524,141.496898327669
        ///105,渡島地方北部,42.2715261571357,140.227924212031
        ///106,渡島地方東部,41.9171303977866,140.730104639953
        ///107,渡島地方西部,41.5890677088811,140.250720331631
        ///110,檜山地方,42.1200892176946,140.117224870458
        ///115,後志地方北部,43.1570832606841,140.766313140274
        ///116,後志地方東部,42.8279967803352,140.848074079286
        ///117,後志地方西部,42.8212795958583,140.381809567057
        ///119,北海道奥尻島,42.1553384492168,139.473175204362
        ///120,空知地方北部,43.8088241 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaPoint {
            get {
                return ResourceManager.GetString("AreaPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap basemap_new_black {
            get {
                object obj = ResourceManager.GetObject("basemap_new_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   110100,札幌中央区,43.0384041572337,141.302077451493
        ///110200,札幌北区,43.1347503224117,141.354056247971
        ///110300,札幌東区,43.1087430953872,141.40131974021
        ///110400,札幌白石区,43.0603253195276,141.425172890005
        ///110500,札幌豊平区,42.9998131682113,141.388947814027
        ///110600,札幌南区,42.9471219985831,141.181575479985
        ///110700,札幌西区,43.0639274394172,141.243072357961
        ///110800,札幌厚別区,43.043337954344,141.473777253169
        ///110900,札幌手稲区,43.115809519746,141.224470978469
        ///111000,札幌清田区,42.9620412063908,141.431388494746
        ///120200,函館市,41.8375442406375,140.925962642598
        ///1203 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CityPoint {
            get {
                return ResourceManager.GetString("CityPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap logo_anied {
            get {
                object obj = ResourceManager.GetObject("logo_anied", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
